(master) Mx builds should use python3 to avoid issues
graalvm/mandrel-packaging pull request #209
Opened 2021-11-29 10:45 UTC by galderz

Closes #208

2021-12-03 09:38 UTC, zakkak requested changes

2021-12-03 09:38 UTC, zakkak commented on build.java
> +                , new EnvVar("MX_PYTHON", "python3")
This only sets the env variable for `mxbuild`.

`mxclean`, `mxversion` and `mandrelVersion` will still run with python 2.

I suggest always adding the variable in `Tasks.Exec.envVars` (even for no mx commands)

2021-12-10 14:13 UTC, galderz commented on build.java
> +                , new EnvVar("MX_PYTHON", "python3")
I don't agree with adding the env var to no mx commands. It serves no purpose. I will look into some way to add it to only the mx commands.

2021-12-14 08:16 UTC, galderz commented
@zakkak I've updated the PR. I've made such that the env var is set for all mx commands. If you're happy with it I'll backport the latest changes to 21.3.

2021-12-14 08:37 UTC, zakkak approved these changes
Thanks @galderz 

LGTM

2021-12-14 08:38 UTC, merged