Added guiding instructions for building Mandrel on macOS
graalvm/mandrel-packaging pull request #343
Opened 2023-06-06 11:24 UTC by galderz

Closes #341

2023-06-06 11:45 UTC, zakkak requested changes
I think we should make clear that we are talking about custom builds. For pre-built binaries it's pretty much the standard procedure.

2023-06-06 11:45 UTC, zakkak commented on README.md
> +Mandrel can be built on a Mac using a supported JDK that contains static libraries.
```suggestion
## Building mandrelJDK on a Mac using a custom build of OpenJDK

Mandrel can be built on a Mac using a custom build of OpenJDK that contains static libraries.
```

2023-06-07 10:58 UTC, galderz commented
@zakkak Applied your commit, squashed it and updated PR.

2023-06-07 11:07 UTC, zakkak commented
@galderz can you please use my red hat email (in the `Co-authored-by` part of the commit message), or just remove it to get the OCA-bot happy?

2023-06-08 07:13 UTC, galderz commented
@zakkak Fixed it

2023-06-08 08:13 UTC, merged