Only build and include svm-foreign when building with JDK > 21
graalvm/mandrel-packaging pull request #398
Opened 2024-01-26 13:39 UTC by zakkak

Since https://github.com/oracle/graal/pull/7980 the foreign API is only
available for JDK >= 22 builds.

2024-01-26 13:52 UTC, jerboaa reviewed
I'm not convinced we need JDK 21 build support, but your mileage may vary.

2024-01-26 13:52 UTC, jerboaa commented on build.java
> -        BuildArgs.of("--no-native", "--dependencies", "SVM,SVM_FOREIGN,GRAAL_SDK,SVM_DRIVER,SVM_AGENT,SVM_DIAGNOSTICS_AGENT")
Could we use this instead?

```
BuildArgs.of("--no-native", "--dependencies", "SVM,GRAAL_SDK,SVM_DRIVER,SVM_AGENT,SVM_DIAGNOSTICS_AGENT" + (Runtime.version().feature() > 21: ",SVM_FOREIGN" ? "");
```

2024-01-26 13:56 UTC, jerboaa commented
Also note that IMO it's an (upstream) bug to add attempt to add `svm-foreign.jar` if `--enable-preview` is specified. I'm pretty sure a Graal master build with labsjdk 21 and `--enable-preview` will fail since in that case the native image generator unconditionally attempts to add the dir containing `svm-foreign.jar` (not present) to the class/module path.

2024-01-26 14:05 UTC, zakkak commented on build.java
> -        BuildArgs.of("--no-native", "--dependencies", "SVM,SVM_FOREIGN,GRAAL_SDK,SVM_DRIVER,SVM_AGENT,SVM_DIAGNOSTICS_AGENT")
Sure

2024-01-26 14:15 UTC, zakkak commented
> Also note that IMO it's an (upstream) bug to add attempt to add `svm-foreign.jar` if `--enable-preview` is specified. I'm pretty sure a Graal master build with labsjdk 21 and `--enable-preview` will fail since in that case the native image generator unconditionally attempts to add the dir containing `svm-foreign.jar` (not present) to the class/module path.

I think that's fixed in https://github.com/oracle/graal/pull/7980

2024-01-26 15:44 UTC, jerboaa approved these changes

2024-01-26 15:48 UTC, jerboaa commented
CI fails due to too new JDK 23:
```
Error: Static modifier mismatch: private void com.oracle.svm.core.thread.Target_java_lang_VirtualThread.notifyJvmtiHideFrames(boolean), private static native void java.lang.VirtualThread.notifyJvmtiHideFrames(boolean)
```

Fixed once this PR merges: https://github.com/oracle/graal/pull/8262

2024-01-26 16:03 UTC, jerboaa commented
> > Also note that IMO it's an (upstream) bug to add attempt to add `svm-foreign.jar` if `--enable-preview` is specified. I'm pretty sure a Graal master build with labsjdk 21 and `--enable-preview` will fail since in that case the native image generator unconditionally attempts to add the dir containing `svm-foreign.jar` (not present) to the class/module path.
> 
> I think that's fixed in [oracle/graal#7980](https://github.com/oracle/graal/pull/7980)

You are right. Thinking some more about this, we don't need the `SVM_FOREIGN` dependency on JDK 23 either. Not sure why the build doesn't outright fail...

2024-01-31 12:29 UTC, zakkak commented
> we don't need the SVM_FOREIGN dependency on JDK 23 either. Not sure why the build doesn't outright fail...

Why is that? All the checks in GraalVM are for `>= 22`.

2024-02-01 11:17 UTC, jerboaa requested changes
It makes little sense to me to try to keep JDK 21 compatibility in `master`. The entire JEP 454 story in GraalVM seems not 100% ready yet. See https://github.com/graalvm/mandrel/issues/678

2024-02-01 11:17 UTC, jerboaa commented on build.java
> +                final Path svmForeign = mandrelJavaHome.resolve(Path.of("lib", "svm-preview", "builder", "svm-foreign.jar"));
`svm-preview` folder is wrong as a target for JDK 22+. See https://github.com/graalvm/mandrel/issues/678 for some details.

2024-02-01 11:18 UTC, jerboaa commented
> > we don't need the SVM_FOREIGN dependency on JDK 23 either. Not sure why the build doesn't outright fail...
> 
> Why is that? All the checks in GraalVM are for `>= 22`.

Sorry, I was wrong. However, there is a different problem with getting `svm-foreign.jar` properly installed for JDK 23. I'll take a look.

2024-02-05 09:49 UTC, jerboaa commented
> > > we don't need the SVM_FOREIGN dependency on JDK 23 either. Not sure why the build doesn't outright fail...
> > 
> > 
> > Why is that? All the checks in GraalVM are for `>= 22`.
> 
> Sorry, I was wrong. However, there is a different problem with getting `svm-foreign.jar` properly installed for JDK 23. I'll take a look.

See #399, which should fix the `svm-foreign.jar` installation.

2024-02-06 19:00 UTC, zakkak commented
> It makes little sense to me to try to keep JDK 21 compatibility in master. The entire JEP 454 story in GraalVM seems not 100% ready yet. See https://github.com/graalvm/mandrel/issues/678

The primary reason for opening this was to prevent build failures when trying to build with JDK 21 so that we can see the actual blocker/issue which is https://github.com/graalvm/mandrel/issues/598

Closing this for now as there are no plans to build `master` with JDK 21, see https://github.com/graalvm/mandrel/issues/598#issuecomment-1912118196

2024-02-06 19:00 UTC, closed without merging