Jbang the release process!
graalvm/mandrel-packaging pull request #58
Opened 2020-09-14 21:01 UTC by zakkak

This aims to ease the release process of Mandrel. @Karm please review and if it looks OK let's try it out with 20.1.0.3.Final :)

2020-09-14 21:04 UTC, zakkak commented
Closes https://github.com/graalvm/mandrel/issues/55

2020-09-15 09:12 UTC, jerboaa requested changes

2020-09-15 09:12 UTC, jerboaa commented on release-scripts/Readme.md
> +For usage information please run `./post-mandrel-release.java -h`
s/post-mandrel-release.java/mandrel-release.java/

2020-09-15 09:12 UTC, jerboaa commented on release-scripts/Readme.md
> +NOTE: This can't be integrated into `post-mandrel-release.java` yet due to
Did you mean `mandrel-release.java`?

2020-09-15 10:19 UTC, zakkak commented on release-scripts/Readme.md
> +For usage information please run `./post-mandrel-release.java -h`
Good catch, thanks!

2020-09-15 10:19 UTC, zakkak commented on release-scripts/Readme.md
> +NOTE: This can't be integrated into `post-mandrel-release.java` yet due to
Good catch, thanks!

2020-09-15 15:48 UTC, jerboaa approved these changes
I'm OK with this, but let @Karm have the final say.

2020-09-16 08:10 UTC, Karm commented
Loading...

2020-09-16 08:20 UTC, Karm requested changes
1. There is hardcoded OpenJDK version we need get rid of
2. I will try to use it in a dummy repo https://github.com/Karm/mandrel-demo-release/ and see how it goes...  I would like to postpone merging this until I can see it works in the dummy repo for me (to be updated).

2020-09-16 08:20 UTC, Karm commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
@zakkak This cannot be hardcoded, it comes from the current Jenkins' : 

```bash
...
export JAVA_VERSION="$(java --version | sed -e 's/.*build \([^) ]*\)).*/\1/;t;d' )"
...
cat >./MANDREL.md <<EOL
This is a dev build of Mandrel from https://github.com/graalvm/mandrel.
Mandrel ${MANDREL_VERSION}
OpenJDK used: ${JAVA_VERSION}
EOL
...
```

So, we have to pull this value from the OpenJDK used...

2020-09-16 08:30 UTC, zakkak commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
So we need to either ensure that jbang will be run using the same OpenJDK used to build the release or we need to just add it as a parameter to the jbang script. Which one do you prefer? I find the latter safer.

2020-09-16 08:32 UTC, zakkak commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
Another way would be to include a file in mandrel sources (or mandrel-packaging sources) that maps mandrel versions to openJDK versions (this will make it easier to reproduce builds in the future as well).

2020-09-16 08:32 UTC, zakkak commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
Graal uses https://github.com/graalvm/mandrel/blob/graal/master/common.json to achieve this

2020-09-16 08:48 UTC, Karm commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
@zakkak I find running jbang with the OpenJDK that is used for the build itself a much better option. The reason is the same as with internal JDK suites and builds of test suites: The run is not polluted by other JDKs, you have one JDK on PATH, no surprises on LD_LIBRARY_PATH, one JAVA_HOME...

if the JDK we are building with breaks jbang, it probably shouldn't be used for the build anyway...

2020-09-16 11:17 UTC, zakkak commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
I am more afraid about issues like "I built mandrel with JDK-A and then ran jbang with JDK-B" and the release readme ends up wrong.

Also what are your thoughts about the file/configuration specifying the correct JDK to use? 

This would allow you to checkout at any time versionA and using mandrel-packaging build mandrel with the correct JDK version, e.g. if you try to build 20.1.0.2 it uses 11.0.8-GA but if you try to build say 20.1.0.5 it would use 11.0.9-GA etc.
And we can even have something similar to graalvm with JAVA_HOME and EXTRA_JAVA_HOMES to define more than one JDK versions that are known to work with the corresponding mandrel version (or that we would like to test, allthough this won't work right in GH actions, but maybe Jenkins can take advantage of it)

2020-09-16 11:46 UTC, zakkak commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
I implemented it to get the version from the underlying runtime for now and we can discuss the "file approach" in another issue.

2020-09-16 11:47 UTC, Karm commented on release-scripts/mandrel-release.java
> +                "OpenJDK used: 11.0.8+10\n";
thx. will do it presently

2020-09-17 12:43 UTC, Karm commented
@zakkak I admit I haven't spent much time on this, but in the amount I did I kinda failed to use it.  Could you help me, preferrably by improving the Readme.md, to get bootstrapped?

1. I created a new GitHub token with sufficient rights (similar to what some of my bots use).
2. I installed jbang! according to the link in the readme (I hereby admit I hadn't had it installed before :) ) 
3. I understood that this is supposed to be run from the Mandrel-packaging repo, which is probably not the case. Are there any env variables needed as they were with the bash version?
```


karm@local:~/workspaceRH/mandrel-packaging/release-scripts (zakkak_release-scripting *%)$ ./mandrel-release.java prepare
[jbang] Resolving dependencies...
[jbang]     Resolving org.eclipse.jgit:org.eclipse.jgit:5.9.0.202009080501-r...Done
[jbang]     Resolving org.eclipse.jgit:org.eclipse.jgit.pgm:5.9.0.202009080501-r...Done
[jbang]     Resolving org.eclipse.jgit:org.eclipse.jgit.gpg.bc:5.9.0.202009080501-r...Done
[jbang]     Resolving info.picocli:picocli:4.5.0...Done
[jbang]     Resolving org.kohsuke:github-api:1.116...Done
[jbang] Dependencies resolved
[jbang] Building jar...
java.nio.file.NoSuchFileException: substratevm/mx.substratevm/suite.py
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:155)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2838)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3329)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3369)
        at MandrelRelease.getCurrentVersion(mandrel-release.java:305)
        at MandrelRelease.call(mandrel-release.java:75)
        at MandrelRelease.call(mandrel-release.java:36)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at MandrelRelease.main(mandrel-release.java:65)
[INFO] Current version is null
java.lang.NullPointerException
```
4. I executed it from the Mandrel repo, having MX on path, JAVA_HOME set....   crashed on this:
```
(mypy2) karm@local:~/workspaceRH/graal/graal (mandrel_20.2)$ /home/karm/workspaceRH/mandrel-packaging/release-scripts/./mandrel-release.java prepare
[INFO] Current version is 20.2.0
java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:645)
        at MandrelRelease.getNewVersion(mandrel-release.java:332)
        at MandrelRelease.call(mandrel-release.java:77)
        at MandrelRelease.call(mandrel-release.java:36)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at MandrelRelease.main(mandrel-release.java:65)

```


Please, let me know if I should start debugging it / figuring what to do or if there are obvious failures you might help me with in the Readme.md file....   Thx  K.

2020-09-17 13:05 UTC, zakkak commented
It's supposed to be run inside the mandrel-repo so 3 was expected (by me) to fail.
I think running it from the mandrel-packaging directory might make more sense indeed, I'll make it ask for the mandrel-repo path as an argument.

Step 4 failed because of https://github.com/graalvm/mandrel/blob/052fce581c89fef8f75dd831464f8bca34828e68/substratevm/mx.substratevm/suite.py#L4

The version there should be 20.2.0.0 instead of 20.2.0 (mandrel versioning vs graal versioning). I will open a PR to fix this on 20.2 and will try to improve the error message of the release script

Thanks for the feedback!

2020-09-17 13:42 UTC, zakkak commented
@Karm I think I tackled all issues. Please try again and let me know.

2020-09-17 14:07 UTC, Karm commented
@zakkak 
```
$ /home/karm/workspaceRH/mandrel-packaging/release-scripts/./mandrel-release.java prepare 
```
now passes over the previous version parsing error and it fails later on:

```
[ERROR] git@github.com:zakkak/mandrel: push not permitted
```

I Ctrl+Fd the code and did:
```
/home/karm/workspaceRH/mandrel-packaging/release-scripts/./mandrel-release.java prepare --fork-name=Karm/mandrel-demo-release
```

To no effect...

2020-09-17 15:50 UTC, zakkak commented
@Karm what's the error in the second case?

>

2020-09-18 07:56 UTC, Karm commented
@zakkak The whole error log (I run it again with you latest updates):

```
(mypy2) karm@local:~/workspaceRH/graal/graal (mandrel/20.2)$ /home/karm/workspaceRH/mandrel-packaging/release-scripts/./mandrel-release.java prepare --fork-name Karm/mandrel-demo-release
[jbang] Building jar...
[INFO] Current version is 20.2.0.0
[INFO] New version will be 20.2.0.1
[INFO] Git remote mandrel-release-fork added and points to git@github.com:Karm/mandrel-demo-release
[INFO] Created new branch release/mandrel-20.2.0.0.Final based on mandrel/20.2
[INFO] Marking ./java-benchmarks/mx.java-benchmarks/suite.py
[INFO] Marking ./regex/mx.regex/suite.py
[INFO] Marking ./sdk/mx.sdk/suite.py
[INFO] Marking ./wasm/mx.wasm/suite.py
[INFO] Marking ./compiler/mx.compiler/suite.py
[INFO] Marking ./vscode/mx.vscode/suite.py
[INFO] Marking ./sulong/mx.sulong/suite.py
[INFO] Marking ./substratevm/mx.substratevm/suite.py
[INFO] Marking ./tools/mx.tools/suite.py
[INFO] Marking ./vm/mx.vm/suite.py
[INFO] Marking ./examples/mx.examples/suite.py
[INFO] Marking ./truffle/mx.truffle/suite.py
[INFO] Updated suites
[INFO] Changes commited
2020-09-18 09:47:56 WARN  KnownHostEntryReader:87 - Known hosts file /home/karm/.ssh/known_hosts contains invalid line 2620:52:0:105f:2054:ff:fe6b:5304 ssh-rsa AAAAB3NzaC1yc2EAABABIwAAAQEA4U6WWmrYKY0tpBJnCVmuKvs13ui94ffi4Tkrc4yi9yVQFefb2Xe5jTc7R0BlpGykSVRMhQnyHkxA+Gtt+L0SxL5yPq/rZ5KkpEhLu9UZPSQWOWelFNzdq3S1xQ5rHN2Awp6FnPYjVJOxevUE2qwWES/GUHEXldzKRjks/wNf0VoOu1yMeMRnKC8bJpFFe9sU/QsOahmenpbaS4YyWBy35uu+wnDnPdFiGjmYVTUg4pcYGw0GfiGwMqDS3i/jbCilzOquuUOTu2bmVU5vSOGG6LoTnw/h4WtNZDhCt3l0YyKW0eClwPkRcSNhThhqeagyDDlBYgebL3wdaHgzjfO7+Q==
java.lang.IllegalArgumentException: Invalid host pattern char in 2620:52:0:105f:5054:ff:fe6b:5304
        at org.apache.sshd.common.util.ValidateUtils$$Lambda$157.00000000F8062D20.apply(Unknown Source)
        at org.apache.sshd.common.util.ValidateUtils.createFormattedException(ValidateUtils.java:213)
        at org.apache.sshd.common.util.ValidateUtils.throwIllegalArgumentException(ValidateUtils.java:179)
        at org.apache.sshd.common.util.ValidateUtils.checkTrue(ValidateUtils.java:168)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.toPattern(HostPatternsHolder.java:283)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.parsePatterns(HostPatternsHolder.java:236)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.parsePatterns(KnownHostEntryReader.java:172)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.parseHostEntry(KnownHostEntryReader.java:129)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.lambda$0(KnownHostEntryReader.java:79)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader$$Lambda$154.00000000F80569F0.accept(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:668)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.readFromFile(KnownHostEntryReader.java:70)
        at org.eclipse.jgit.internal.transport.sshd.OpenSshServerKeyDatabase$HostKeyFile.reload(OpenSshServerKeyDatabase.java:589)
        at org.eclipse.jgit.internal.transport.sshd.OpenSshServerKeyDatabase$HostKeyFile.get(OpenSshServerKeyDatabase.java:571)
        at org.eclipse.jgit.internal.transport.sshd.OpenSshServerKeyDatabase.lookup(OpenSshServerKeyDatabase.java:182)
        at org.eclipse.jgit.internal.transport.sshd.JGitServerKeyVerifier.lookup(JGitServerKeyVerifier.java:72)
        at org.eclipse.jgit.internal.transport.sshd.JGitClientSession.resolveAvailableSignaturesProposal(JGitClientSession.java:403)
        at org.apache.sshd.common.session.helpers.AbstractSession.resolveAvailableSignaturesProposal(AbstractSession.java:2173)
        at org.apache.sshd.common.session.helpers.AbstractSession.sendKexInit(AbstractSession.java:2098)
        at org.eclipse.jgit.internal.transport.sshd.JGitClientSession.sendKexInit(JGitClientSession.java:315)
        at org.apache.sshd.client.session.AbstractClientSession.initializeKeyExchangePhase(AbstractClientSession.java:259)
        at org.apache.sshd.client.session.ClientSessionImpl.<init>(ClientSessionImpl.java:104)
        at org.eclipse.jgit.internal.transport.sshd.JGitClientSession.<init>(JGitClientSession.java:97)
        at org.eclipse.jgit.internal.transport.sshd.JGitSshClient$JGitSessionFactory.doCreateSession(JGitSshClient.java:358)
        at org.apache.sshd.client.session.SessionFactory.doCreateSession(SessionFactory.java:32)
        at org.apache.sshd.common.session.helpers.AbstractSessionFactory.createSession(AbstractSessionFactory.java:46)
        at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.sessionCreated(AbstractSessionIoHandler.java:40)
        at org.apache.sshd.common.io.nio2.Nio2Connector$ConnectionCompletionHandler.onCompleted(Nio2Connector.java:156)
        at org.apache.sshd.common.io.nio2.Nio2Connector$ConnectionCompletionHandler.onCompleted(Nio2Connector.java:122)
        at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38)
        at org.apache.sshd.common.io.nio2.Nio2CompletionHandler$$Lambda$145.00000000F800C320.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
        at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:831)
2020-09-18 09:47:56 WARN  KnownHostEntryReader:87 - Known hosts file /home/karm/.ssh/known_hosts contains invalid line 2620:52:0:1330:21a:4aff:fe16:1e2 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4U6WWmrYKY0tpBJnCVmuKvs13ui94ffi4Tkrc4yi9yVQFefb2Xe5jTc7R0BlpGykSVRMhQnyHkxA+Gtt+L0SxL5yPq/rZ5KkpEhLu9UZPSQWOWelFNzdq3S1xw5rHN2Awp6FnPYjVJOxevUE2qwWZS/GUHEXldzKRjks/wNf0VoOu1yMeMRnKC8bJpFFe9sU/QsOahmenpbaS4YyWBy35uu+wnDnPdFiGjmYVTUg4pcYGw0GfiGwMqDS3i/jbCilzOquuUOTu2bmVU5vSOGG6LoTnw/h4WtNZDhCt3l0YyKW0eClwPkRcSNhThhqeagyDDlBYgebL3wdaHgzjfO7+Q==
java.lang.IllegalArgumentException: Invalid host pattern char in 2620:52:0:1340:21a:4aff:fe16:1e2
        at org.apache.sshd.common.util.ValidateUtils$$Lambda$157.00000000F8062D20.apply(Unknown Source)
        at org.apache.sshd.common.util.ValidateUtils.createFormattedException(ValidateUtils.java:213)
        at org.apache.sshd.common.util.ValidateUtils.throwIllegalArgumentException(ValidateUtils.java:179)
        at org.apache.sshd.common.util.ValidateUtils.checkTrue(ValidateUtils.java:168)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.toPattern(HostPatternsHolder.java:283)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.parsePatterns(HostPatternsHolder.java:236)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.parsePatterns(KnownHostEntryReader.java:172)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.parseHostEntry(KnownHostEntryReader.java:129)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader.lambda$0(KnownHostEntryReader.java:79)
        at org.eclipse.jgit.internal.transport.sshd.KnownHostEntryReader$$Lambda$154.00000000F80569F0.accept(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$Itera [...]

2020-09-18 08:01 UTC, Karm commented
@zakkak BTW it is legal to have 1 more GitHub account used as a "bot" or a "service", e.g. mine is https://github.com/KarmBot  
It might ease the debug if you used your bot account with some fake repo on that clean RHEL 8 VM. Errors like silently pushing to ```[ERROR] git@github.com:zakkak/mandrel: push not permitted``` that work for you but no one else would pop up immediately then.

2020-09-18 08:37 UTC, zakkak commented
> I think this PR is too much dependent on what you already have configured and set on your own system and that's why it runs just fine for you....

I wouldn't say so. Till now one issue was the wrong version in branch 20.2 and the others were related to unclear documentation:
* one was about the location from where you should run the script
* and the other about the --fork-name whose default value is my fork (which I am happy to change, and make it a required parameter). 

The latest issue is the only one that seems to be related to my environment but for it to appear I would have to run the sequence:
```
$ release-scripts/./mandrel-release.java prepare
$ release-scripts/./mandrel-release.java prepare --fork-name myaccount/mandrel-fork
```

So even with a clean env and a demo/bot account it would be hard to detect :) (since I would know that --fork-name is needed and would probably not execute that sequence)

The problem was that https://github.com/zakkak/mandrel-packaging/blob/3ee9149edfd47b3e436f0c3cc4f874a8da2ce266/release-scripts/mandrel-release.java#L123 did not force-add/update the remote if it already existed. So in your case it was created in the first run pointing to `zakkak/mandrel` and in the second run it was **not** updated to point to `Karm/mandrel-demo-release` (but was not detected so it failed silently).

> WDYT?

I can give the new version a "clean room" spin, but it will take me some time to prepare the env and set up a new GH account. So if it's not too frustrating could you please give it another spin?

2020-09-18 08:41 UTC, Karm commented
@zakkak It's not frustrating for me, I'm cool. I was more worried about you, picturing you at the other end of the PR getting like "OMG, why Karm ain't merging yet!?". I will cycle back to it in some minutes / soon and try again.

2020-09-18 09:23 UTC, zakkak commented
> I was more worried about you, picturing you at the other end of the PR getting like "OMG, why Karm ain't merging yet!?". I will cycle back to it in some minutes / soon and try again.

Nuh, everything you pointed out makes sense and should be fixed. That's the purpose of the review after all :)
Thanks

2020-09-18 11:08 UTC, Karm commented
@zakkak I cleared .git/config, updated to your latest code and run it again. It went further than before, failing on the below mark now:

```
...
[INFO] Changes pushed to remote mandrel-release-fork
[INFO] Checked out mandrel/20.2
[ERROR] {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

2020-09-18 11:19 UTC, zakkak commented
> @zakkak I cleared .git/config, updated to your latest code and run it again. It went further than before, failing on the below mark now:
> 
> ```
> ...
> [INFO] Changes pushed to remote mandrel-release-fork
> [INFO] Checked out mandrel/20.2
> [ERROR] {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
> ```
> 
> Note the branch was actually created: https://github.com/Karm/mandrel-demo-release/tree/release/mandrel-20.2.0.0.Final
> ...but it seems opening PR failed?

Hmmm this is probably because you are trying to open a PR in the same repository (both your base and target are Karm/mandrel-demo-release). I didn't think we need to support this since we always work on forks of `graalvm/mandrel`.
I can add support for it though.

2020-09-18 20:14 UTC, zakkak commented
> I can add support for it though.

@Karm Please let me know if you need this :)

2020-09-19 06:21 UTC, Karm commented
@zakkak I think it makes sense for testing it and opening a PR from one repo to the same repo is a legit move...there should not be anything preventing it in the GH API, is it?

2020-09-23 10:48 UTC, zakkak commented
@Karm this is now implemented and tested with https://github.com/zakkak/mandrel-mirror
If you plan to test yourself note that you will need to create a milestone 20.1.0.3.Final in your mirror repo and apply a patch like the following to mandrel-release

```diff
diff --git a/release-scripts/mandrel-release.java b/release-scripts/mandrel-release.java
index d75b36b..160eb29 100755
--- a/release-scripts/mandrel-release.java
+++ b/release-scripts/mandrel-release.java
@@ -39,7 +39,7 @@ import java.util.stream.Stream;
 class MandrelRelease implements Callable<Integer> {
 
     public static final String GITFORGE_URL = "git@github.com:";
-    public static final String REPOSITORY_NAME = "graalvm/mandrel";
+    public static final String REPOSITORY_NAME = "zakkak/mandrel-mirror";
 
     @CommandLine.Parameters(index = "0", description = "The kind of steps to execute, must be one of \"prepare\" or \"release\"")
     private String phase;
@@ -329,7 +329,7 @@ class MandrelRelease implements Callable<Integer> {
             } else {
                 pullRequest.addAssignees(Collections.singletonList(zakkak));
             }
-            pullRequest.requestReviewers(reviewers);
+//            pullRequest.requestReviewers(reviewers);
 
             info("Pull request " + pullRequest.getHtmlUrl() + " created");
         } catch (IOException e) {
```

2020-09-24 06:33 UTC, Karm commented
@zakkak THX. Gonna try it all again and report today, UTC+2

2020-09-25 12:22 UTC, Karm commented
Hi, @zakkak, thank you for the update.

It went automatically without errors all the way to creating this on its own:

https://github.com/Karm/mandrel-demo-release/pull/5

What concerns me is the text of the PR. While it is releasing 20.2.0.0, the text talks about 20.1 branch, which is weird:

```
git checkout mandrel/20.1
git pull upstream mandrel/20.1
git tag -a mandrel-20.2.0.0.Final -m "mandrel-20.2.0.0.Final" -s
git push upstream mandrel-20.2.0.0.Final
```  

WDYT?

2020-09-25 12:36 UTC, zakkak commented
> What concerns me is the text of the PR. While it is releasing 20.2.0.0, the text talks about 20.1 branch, which is weird:
> 
> ```
> git checkout mandrel/20.1
> git pull upstream mandrel/20.1
> git tag -a mandrel-20.2.0.0.Final -m "mandrel-20.2.0.0.Final" -s
> git push upstream mandrel-20.2.0.0.Final
> ```
> 
> WDYT?

Good catch, that's what you get for hardcoding part of the text :) on it!

2020-09-25 12:42 UTC, zakkak commented
Fixed! see https://github.com/zakkak/mandrel-mirror/pull/5

2020-09-25 13:19 UTC, Karm commented
Loading...

2020-09-25 13:44 UTC, Karm commented
@zakkak  I deleted the Karm/mandrel-demo-release repo and I pushed there again what we have in the mandrel...

Then I run the latest code and got:

```
[INFO] Changes pushed to remote mandrel-release-fork
[INFO] Checked out mandrel/20.2
org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
        at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:495)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:420)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363)
        at org.kohsuke.github.Requester.fetch(Requester.java:74)
        at org.kohsuke.github.GHRepository.createPullRequest(GHRepository.java:1472)
        at MandrelRelease.openPR(mandrel-release.java:304)
        at MandrelRelease.call(mandrel-release.java:113)
        at MandrelRelease.call(mandrel-release.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at MandrelRelease.main(mandrel-release.java:72)
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/Karm/mandrel-demo-release/pulls
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:734)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
        at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:326)
        at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:91)
        at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74)
        at org.kohsuke.github.Requester$$Lambda$226.00000000E82C4510.apply(Unknown Source)
        at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412)
        ... 14 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/Karm/mandrel-demo-release/pulls
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
        at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:69)
        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:400)
        ... 14 more
[ERROR] {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

It seems the branch is created there:

https://github.com/Karm/mandrel-demo-release/tree/release/mandrel-20.2.0.0.Final
  
And yet for some reason, the PR creation fails...

WDYT?

2020-09-25 13:48 UTC, zakkak commented
GH says that your base is for the PR is wrong. 

Did you apply something similar to the below before testing?
```diff
diff --git a/release-scripts/mandrel-release.java b/release-scripts/mandrel-release.java
index d75b36b..160eb29 100755
--- a/release-scripts/mandrel-release.java
+++ b/release-scripts/mandrel-release.java
@@ -39,7 +39,7 @@ import java.util.stream.Stream;
 class MandrelRelease implements Callable<Integer> {
 
     public static final String GITFORGE_URL = "git@github.com:";
-    public static final String REPOSITORY_NAME = "graalvm/mandrel";
+    public static final String REPOSITORY_NAME = "zakkak/mandrel-mirror";
 
     @CommandLine.Parameters(index = "0", description = "The kind of steps to execute, must be one of \"prepare\" or \"release\"")
     private String phase;
@@ -329,7 +329,7 @@ class MandrelRelease implements Callable<Integer> {
             } else {
                 pullRequest.addAssignees(Collections.singletonList(zakkak));
             }
-            pullRequest.requestReviewers(reviewers);
+//            pullRequest.requestReviewers(reviewers);
 
             info("Pull request " + pullRequest.getHtmlUrl() + " created");
         } catch (IOException e) {
```

2020-09-25 14:00 UTC, Karm commented
@zakkak   I did...

```
index 70b2b7f..a702777 100755
--- a/release-scripts/mandrel-release.java
+++ b/release-scripts/mandrel-release.java
@@ -39,7 +39,7 @@ import java.util.stream.Stream;
 class MandrelRelease implements Callable<Integer> {
 
     public static final String GITFORGE_URL = "git@github.com:";
-    public static final String REPOSITORY_NAME = "graalvm/mandrel";
+    public static final String REPOSITORY_NAME = "Karm/mandrel-demo-release";
 
     @CommandLine.Parameters(index = "0", description = "The kind of steps to execute, must be one of \"prepare\" or \"release\"")
     private String phase;
@@ -329,7 +329,7 @@ class MandrelRelease implements Callable<Integer> {
             } else {
                 pullRequest.addAssignees(Collections.singletonList(zakkak));
             }
-            pullRequest.requestReviewers(reviewers);
+            //pullRequest.requestReviewers(reviewers);

```


Can you see here something missing? Missing branch?

https://github.com/Karm/mandrel-demo-release/branches

Locally:

```
(mypy2) karm@local:~/workspaceRH/graal/graal (mandrel/20.2)$ git status
On branch mandrel/20.2
nothing to commit, working tree clean
```

Config:

```
(mypy2) karm@local:~/workspaceRH/graal/graal (mandrel/20.2)$ cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:Karm/graal.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "upstream"]
        url = https://github.com/oracle/graal.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[remote "adinn"]
        url = https://github.com/adinn/graal.git
        fetch = +refs/heads/*:refs/remotes/adinn/*
[branch "debug_info_prototype"]
        remote = adinn
        merge = refs/heads/debug_info_prototype
[gitg]
        mainline = refs/heads/master
[remote "mandrel"]
        url = https://github.com/graalvm/mandrel
        fetch = +refs/heads/*:refs/remotes/mandrel/*
[user]
        signingkey = AD43D0844F68E639B706A47109654A8CCB66212A
        email = karm@redhat.com
[branch "20.1"]
        remote = mandrel
        merge = refs/heads/20.1
[remote "mandrel-demo-release"]
        url = git@github.com:Karm/mandrel-demo-release.git
        fetch = +refs/heads/*:refs/remotes/mandrel-demo-release/*
[remote "severin"]
        url = https://github.com/jerboaa/graal.git
        fetch = +refs/heads/*:refs/remotes/severin/*
[remote "foivos"]
        url = https://github.com/zakkak/mandrel.git
        fetch = +refs/heads/*:refs/remotes/foivos/*
[remote "mandrel-release-fork"]
        url = git@github.com:Karm/mandrel-demo-release
        fetch = +refs/heads/*:refs/remotes/mandrel-release-fork/*

```

2020-09-25 14:02 UTC, zakkak commented
> Can you see here something missing? Missing branch?
> 
> https://github.com/Karm/mandrel-demo-release/branches

That's it I see no `mandrel/20.2` branch there :)

2020-09-25 14:13 UTC, Karm approved these changes
@zakkak That was it :)

https://github.com/Karm/mandrel-demo-release/pull/1

LGTM!

2020-09-25 14:14 UTC, Karm commented
@zakkak Merge at your convenience....

2020-09-25 14:16 UTC, zakkak commented
Thanks for all the help @Karm !

2020-09-25 14:16 UTC, merged