All upstream Jenkins jobs related to Mandrel are encoded in Jenkins DSL now
graalvm/mandrel-packaging pull request #81
Opened 2020-12-09 14:21 UTC by Karm

How one works with it:
1. Do a change in jenkins/*, have it merged.
2. Click build now on this job https://ci.modcluster.io/view/Mandrel/job/dsl-mandrel-jobs/
3. It fails the first time, because your changes are pending script approval; Open https://ci.modcluster.io/scriptApproval/ and approve
4. Run step 2. again and it is all regenerated as one would expect.

Ad step 3.: I am investigating if it is really necessary and what additional security it actually brings.

Readme/docs on the syntax: https://ci.modcluster.io//plugin/job-dsl/api-viewer/index.html

2020-12-15 22:03 UTC, Karm commented
@zakkak Nudge nudge

2020-12-15 23:03 UTC, zakkak requested changes
@Karm this is a great improvement but the fact that you have to replicate so many things seems wrong to me.

E.g., why can't we have a single `mandrel_linux_build.groovy` that will be able to build 20.1, 20.2, 20.3, and master using a matrix of configurations?

I also don't understand the purpose of `build.sh` and `buildLabsJDK.sh` since they are not used in any job and they don't seem generic.

Additionally (Jenkins DSL newbie question), is there any way to have some form of library that you can then reuse across the different jobs?

2020-12-15 23:09 UTC, zakkak commented on build.sh
> +export MANDREL_HOME="$(pwd)/mandrel-java11-${MANDREL_VERSION_UNTIL_SPACE}"
It looks like you have said this yourself in https://github.com/graalvm/mandrel-packaging/issues/75 as well :)

2020-12-16 16:55 UTC, Karm commented
@zakkak THX for the feedback. I will comment & fix step by step. First:  buildLabsJDK.sh and  build.sh are there by mistake. I used them locally for myself, never intended to push them :facepalm:   Lemme fix that...

2020-12-17 12:45 UTC, Karm commented on jenkins/jobs/mandrel_20_2_linux_build.groovy
> +            trigger(['mandrel-linux-integration-tests/MANDREL_VERSION=20.2,label=el8']) {
@zakkak My intention was to run the whole Q TS with 20.1 and then latest, i.e. 20.3.  This is purely a matter of executor resources. We should definitely leave it on in the GitHub Workflow.

2020-12-17 12:49 UTC, Karm commented on jenkins/jobs/mandrel_20_3_linux_build.groovy
> +            trigger(['mandrel-linux-quarkus-tests/LABEL=el8,MANDREL_VERSION=20.3,QUARKUS_VERSION=1.10.2.Final/',
@zakkak Definitely yes on GitHub Workflow. Not sure here. Is it more valuable to follow 1.10 branch (rather than 1.10. tags) and leave master for GitHub Workflow? I am afraid of using limited executor time on Jenkins on Quarkus master...   
Let's push as much Linux amd64 to GitHub Workflow as possible.

Matrix configuration shouldn't block the PR IMHO.

2020-12-17 12:58 UTC, Karm commented
@zakkak /me testing new updates


> E.g., why can't we have a single mandrel_linux_build.groovy that will be able to build 20.1, 20.2, 20.3, and master using a matrix of configurations?

It can be done as a matrix job. But then it would always trigger a publisher that would run tests even for versions that weren't built...  Maybe I am lacking Jenkins DSL-fu on this one. I managed to get rid of the duplicated shell by stuffing it into a separate file and I will be trimming that file further down by delegating tasks to build.java.

> I also don't understand the purpose of build.sh and buildLabsJDK.sh since they are not used in any job and they don't seem generic.

A stupid mistake of mine. These files should not have been committed at all. They are gone now.

> Additionally (Jenkins DSL newbie question), is there any way to have some form of library that you can then reuse across the different jobs?

I am no Jenkins DSL pro either. I used it once before and to my best knowledge, that would have to be converted into Jenkins Pipelines syntax to re-use components like libraries. I wouldn't bother with that at this point.

My overall intention for this PR is:

 * to get rid of clicking in the GUI and to enable us to e.g. bump a Quarkus version or to add/remove Mandrel version with a single text commit
 * allow me to easily create a similar job(s) on other Jenkins instances as/if needed

2020-12-17 13:03 UTC, Karm commented on jenkins/jobs/mandrel_linux_quarkus_container_tests.groovy
> +        stringParam('CONTAINER_IMAGE', 'quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11', 'Mandrel builder image.')
Executor resources and coverage by GitHub Workflows.

2020-12-17 13:05 UTC, Karm commented on jenkins/jobs/mandrel_20_1_linux_build.groovy
> +                        'openjdk-11-latest'
These JDKs are already present on the executors hosts (Linux and Windows). A job that updates them will be created in Jenkins DSL too - not present in this PR.

2020-12-17 13:50 UTC, Karm commented
@zakkak  It should look better now.

BTW: To test it, I had to leave 
```
        choiceParam(
                'PACKAGING_REPOSITORY',
                [
                        'https://github.com/Karm/mandrel-packaging.git',
```
there and port scripts to 20.1 branch: #82 

I will swap it to https://github.com/graalvm/mandrel-packaging and edit the branches (jenkins -> master and 20.1-jenkins to 20.1) before merging.

2020-12-17 13:59 UTC, zakkak approved these changes
LGTM! 

>  I managed to get rid of the duplicated shell by stuffing it into a separate file and I will be trimming that file further down by delegating tasks to build.java.

The only "missing" thing I see is the trimming of the build scripts by delegating tasks to `build.java`, but I don't think this is a strong requirement.

2020-12-21 10:45 UTC, merged